### ISSUE TITLE
Allow third parties to bulk-add assets to the library

### ISSUE THREAD

**Issue by doradoro** [Calinou/godot-asset-library-laravel#303] opened 2021-06-10 16:56 UTC
It would be great to mass import assets like Materials and finish in a BlenderKit style search inside godot editor. I mean: be able to let the free asset libraries to add their own free content to the godot library in bulk as a way to promote their services. Some kind of API or something like that...

**Comment by Calinou** [comment] 2021-06-10 17:05
The issue is that PBR materials need to be imported with Godot `.tres` files to be really usable out of the box. Otherwise, people have to set up the materials by hand, so you don't gain much time compared to downloading the textures manually and placing them in your project.

**Comment by doradoro** [comment] 2021-06-10 17:08
I was thinking about doing an automated import of materials due to this
problem (based on file names) . I think there is no standard related to
materials and someone should create it...

**Comment by Calinou** [comment] 2021-06-10 17:09
> I was thinking about doing an automated import of materials due to this
problem (based on file names) . I think there is no standard related to
materials and someone should create it...

Creating a standard is easier said than done :slightly_smiling_face: 

Loading textures into a StandardMaterial3D/ORMMaterial3D based on naming conventions is possible, but it's difficult to get it right for all textures available online. See also https://github.com/godotengine/godot-proposals/issues/2316.

**Comment by doradoro** [comment] 2021-06-10 17:48
Do you know if there are some kind of LOD but for materials?

**Comment by doradoro** [comment] 2021-06-10 20:08
Many thanks for your wisdom! This topic is so complex that I needed to
study it a few times and I still don't understand the details.

**Comment by Calinou** [comment] 2021-09-01 21:10
Closing, as this will not be implemented.

**Closed by Calinou** 2021-09-01 21:10 UTC
Labels: enhancement
